apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.service.image }}:{{ .Values.service.tag }}"
          imagePullPolicy: {{ .Values.service.imagePullPolicy }}
          {{- if .Values.service.port }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- end }}
          env:
            {{- if .Values.service.port }}
            - name: PORT
              value: "{{ .Values.service.port }}"
            {{- end }}
            {{- range $key, $val := .Values.service.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- if .Values.service.secret }}
          envFrom:
            - secretRef:
                name: {{ .Values.service.secret }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
---
{{- if .Values.service.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
{{- end }}
