{{- if .Values.service.vaultPath }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.service.name }}-secret
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: {{ .Values.service.name }}-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.service.vaultPath }}
{{- end }}
