name: CI - Node

on:
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.ci.outputs.tag }}

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

      - name: Build check
        run: npm run build
